[3.045256965882168e-08, 2.7907366448284925e-08, 2.5618095847968888e-08, 2.3559832712131873e-08, 2.170440107992943e-08]
None
[8.254866028732651e-08, 7.38348676009216e-08, 6.623801184003253e-08, 5.959154198715758e-08, 5.3757731832045144e-08]
None
[4.8619747378962114e-08, 4.408139686718755e-08, 4.0058709070477097e-08, 3.648378187093708e-08, 3.32987254272847e-08]
None
/home/steinerm/.conda/envs/parallel/lib/python3.10/site-packages/scipy/integrate/_quadpack_py.py:1151: IntegrationWarning: The occurrence of roundoff error is detected, which prevents 
  the requested tolerance from being achieved.  The error may be 
  underestimated.
  quad_r = quad(f, low, high, args=args, full_output=self.full_output,
[2.2485706543132184e-06, 1.7577777173720568e-06, 1.3931575956137659e-06, 1.117893344907049e-06, 9.070640072900221e-07]
None
[3.110913647499531e-07, 2.666985758174456e-07, 2.2992838913372824e-07, 1.9926590102737702e-07, 1.735367118895438e-07]
None
[1.5181993404618356e-07, 1.333894063344636e-07, 1.1766653795342089e-07, 1.0418948082978903e-07, 9.258389689876845e-08]
None
[7.43461139528208e-07, 6.149883256501841e-07, 5.130022966182544e-07, 4.312357435638862e-07, 3.6507470210648224e-07]
None
[1.0165786546459232e-05, 7.180731422937807e-06, 5.206518247572142e-06, 3.861498322165839e-06, 2.9211320482950195e-06]
None
[0.00010482294899960895, 5.901297804377516e-05, 3.54568531441172e-05, 2.2448303039816042e-05, 1.4837195949318697e-05]
None
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd-midway2-0167: error: *** JOB 22244571 ON midway2-0167 CANCELLED AT 2022-08-31T02:13:17 DUE TO TIME LIMIT ***
slurmstepd-midway2-0167: error: *** STEP 22244571.0 ON midway2-0167 CANCELLED AT 2022-08-31T02:13:17 DUE TO TIME LIMIT ***
